project_name: chewa

dist: .bin

before:
  hooks:
    - go mod tidy
    
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64